# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

RED="$(tput bold)$(tput setaf 1)"
GREEN="$(tput bold)$(tput setaf 2)"
YELLOW="$(tput bold)$(tput setaf 3)"
PURPLE=$(tput setaf 141)
NORMAL=$(tput sgr0)

function custom_ps1 {

  NUM_JOBS=$(jobs | wc -l)

  if [ "${NUM_JOBS}" -gt "0" ]; then
    JOBS_LABEL=" \[${GREEN}\][${NUM_JOBS}]\[\033[00m\]"
  else
    JOBS_LABEL=""
  fi

  git branch &>/dev/null

  if [ $? -eq 0 ]; then
    GIT_BRANCH=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ \1/")

    if [[ $(git status -s 2> /dev/null | head -n1) =~ '??' ]]; then
      GIT_COLOR="${PURPLE}"
    elif [[ $(git status 2> /dev/null | tail -n1) =~ nothing ]]; then
      GIT_COLOR="${GREEN}"
    else
      GIT_COLOR="${RED}"
    fi
  else
    GIT_BRANCH=""
    GIT_COLOR="${NORMAL}"
  fi

  PS1="\[\033[01;32m\]\u@\h\[\033[00m\] ${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\w\[\033[00m\]${JOBS_LABEL}\[${YELLOW}\]${GIT_BRANCH}\[\033[00m\]\[${GIT_COLOR}\] ▶\[${NORMAL}\] "
}

if [ "$color_prompt" = yes ]; then
    PROMPT_COMMAND=custom_ps1
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Trim path directories
export PROMPT_DIRTRIM=1

# Love
export EDITOR=vim

# Enable vi mode in bash
set -o vi

# Enable Ctrl+L in vi mode
bind -m vi-insert "\C-l":clear-screen

# Local bin path
if [ -d ~/.bin ]; then
  export PATH=~/.bin:$PATH
fi

# Disable flow control. Ctrl-s + Ctrl-q
stty stop ''
stty start ''
stty -ixon
stty -ixoff

# Disalbe capslock
if which setxkbmap  >/dev/null; then
  setxkbmap -option caps:ctrl_modifier
fi

# Keep the secrets, in secret
if [ -f ~/.bash_secrets ]; then
    source ~/.bash_secrets
fi

# Awesome command search
if [ -f ~/.fzf.bash ]; then
    source ~/.fzf.bash
fi

# NodeJs bin
export PATH=./node_modules/.bin:$PATH

# Rbenv path
export RBENV_ROOT="$HOME/.rbenv"
if [ -d "$RBENV_ROOT" ]; then
  export PATH="$RBENV_ROOT/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Google Chrome Devopt Tools
export PATH=$PATH:$HOME/Development/depot_tools

# Go environment
if [ -d "$HOME/Development/go" ]; then
  export GOPATH="$HOME/Development/go"
  export PATH="$PATH:$GOPATH/bin"
fi

# Ruby environment
if [ -f "$HOME/.rvm/scripts/rvm" ]; then
  source "$HOME/.rvm/scripts/rvm"
fi

# Rust environment
if [ -f "$HOME/.cargo/env" ]; then
  source $HOME/.cargo/env
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
