#!/bin/bash

# CD
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
alias cd...='cd ../..'

# LS
alias ls='ls --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alFh'

# GIT
alias gap='git add -p'
alias gd='git diff'
alias gdc='git diff --cached'
alias gg='git grep -n -C2 --color=always'
alias gg0='git grep -n -C0 --color=always'
alias gitroot='cd $(git rev-parse --show-cdup)'
alias gl='git log'
alias gm='git commit -m'
alias gma='git commit --amend --no-edit'
alias gp='git publish'
alias gpr='git pull --rebase'
alias gs='git status -s'

# SCREEN
alias sc='screen -q'
alias sd='screen -d'
alias sl='screen -ls'
alias sr='screen -r'

# UTILS
alias open='xdg-open > /dev/null 2>&1'

notes() {
  NEW_NOTE="New note"
  NOTES_PATH="${HOME}/.notes"
  NOTES=$(find "${NOTES_PATH}" -iname '*.md')
  FILE=$(printf "%s\n%s" "${NOTES}" "${NEW_NOTE}" | fzf --prompt='Choose a file: ')

  if [ "${FILE}" == "${NEW_NOTE}" ]; then
    vim +"cd ${NOTES_PATH}"
  else
    [[ ! -z "${FILE}" ]] && vim "${FILE}"
  fi
}

# Function to restore broken ssh-agent session
# https://coderwall.com/p/_s_xda/fix-ssh-agent-in-reattached-tmux-session-shells
fixssh() {
  for key in SSH_AUTH_SOCK SSH_CONNECTION SSH_CLIENT; do
    if (tmux show-environment | grep "^${key}" > /dev/null); then
      value=`tmux show-environment | grep "^${key}" | sed -e "s/^[A-Z_]*=//"`
      export ${key}="${value}"
    fi
  done
}
